// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_courses_default = defineTool({
  name: "search_courses",
  title: "Search courses",
  description: "Search the EduZambia course catalog by title or subject keyword.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to match against course titles and subjects."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results to return (default 10).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("courses").select("id, title, subject, grade_level, description").or(`title.ilike.%${query}%,subject.ilike.%${query}%`).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-assignments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_assignments_default = defineTool2({
  name: "list_my_assignments",
  title: "List my assignments",
  description: "List the signed-in user's assignments with optional status filter.",
  inputSchema: {
    status: z2.enum(["pending", "submitted", "graded"]).optional().describe("Filter by assignment status."),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("assignments").select("id, title, subject, due_date, status").eq("user_id", ctx.getUserId()).order("due_date", { ascending: true }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { assignments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/ask-ai-tutor.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var ask_ai_tutor_default = defineTool3({
  name: "ask_ai_tutor",
  title: "Ask BrightSphere AI Tutor",
  description: "Ask the EduZambia AI tutor a question about the Zambian ECZ curriculum. Returns a plain-text tutor response.",
  inputSchema: {
    question: z3.string().trim().min(1).describe("The student's question."),
    grade: z3.string().optional().describe("Grade level (e.g. 'Grade 9', 'Grade 12')."),
    subject: z3.string().optional().describe("Subject area, e.g. 'Mathematics', 'Biology'.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ question, grade, subject }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const apiKey = process.env.LOVABLE_API_KEY;
    if (!apiKey) {
      return { content: [{ type: "text", text: "AI gateway not configured" }], isError: true };
    }
    const system = `You are BrightSphere AI, a Zambian ECZ curriculum tutor. Be clear, encouraging, and step-by-step.${grade ? ` Target grade: ${grade}.` : ""}${subject ? ` Subject: ${subject}.` : ""}`;
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Lovable-API-Key": apiKey
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: system },
          { role: "user", content: question }
        ]
      })
    });
    if (!res.ok) {
      const t = await res.text();
      return { content: [{ type: "text", text: `AI error ${res.status}: ${t}` }], isError: true };
    }
    const data = await res.json();
    const answer = data?.choices?.[0]?.message?.content ?? "";
    return {
      content: [{ type: "text", text: answer }],
      structuredContent: { answer }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pmoxtvuhsupfpfcstlur";
var mcp_default = defineMcp({
  name: "eduzambia-mcp",
  title: "EduZambia MCP",
  version: "0.1.0",
  instructions: "Tools for EduZambia (Nexus Learning). Use `search_courses` to find ECZ-aligned courses, `list_my_assignments` to see the signed-in student's assignments, and `ask_ai_tutor` to get tutor answers for Zambian curriculum questions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_courses_default, list_my_assignments_default, ask_ai_tutor_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
